apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  name: istio
  namespace: addon-istio-installer-ns
spec:
  eks:
    minSize: 4
    maxSize: 12
    configuration:
      volumes:
        - name: /dev/xvda
          type: gp2
          size: 128
      taints:
        - key: ig/istiocontrol
          effect: NoSchedule
        - key: ig/istiocontrol
          effect: NoExecute
      instanceType: "m5.xlarge"
      tags:
        - key: eks.k8s.io/instancegroup
          value: istio
        - key: Namespace
          value: addon-istio-installer-ns
        - key: "intuit:asset_id"
          {{- if .Values.intuit.assetId }}
          value: {{ .Values.intuit.assetId }}
          {{- end }}
