# Default values for istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
istioInstallerImage:
  repository: docker.intuit.com/services/mesh/mesh-aviso/service/ballast
  tag: v2.1.10
  pullPolicy: Always

env:
  meshVersion: 1.10.42
  clusterName: jimin-argo-mesh
  awsRegion: us-west-2
  clusterEnv: preprod
  clusterShortName: jimin-argo-mesh
  accountNumber: 681402570415
  apiServerURL: https://eksapi-jimin-argo-mesh-36b18be574427492.elb.us-west-2.amazonaws.com
  installerNamespace: addon-istio-installer-ns
  addonVersion: v2.1.10
  vpcID: vpc-0787dd745fc6734d7
  iksVersion: v2.17.6
  privateSubnetes: "[subnet-07bb649ff2be8975e subnet-0a441e7896b75e192 subnet-0521c90adccd8b37d]"
  avisoHost: aviso-e2e.api.intuit.com

intuit:
  assetId: "4615081310646958673"
